# Generated by Django 2.1.4 on 2018-12-10 09:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('iso3', models.CharField(max_length=3, unique=True)),
                ('num_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('phone_code', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.SmallIntegerField()),
                ('hdop', models.FloatField(verbose_name='Horizontal dilution of precision')),
                ('registration_date', models.DateTimeField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField()),
                ('uuid', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='households', to='adgg.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
