# Generated by Django 2.1.5 on 2019-01-22 09:08

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('altitude', models.SmallIntegerField(blank=True, null=True)),
                ('hdop', models.FloatField(blank=True, null=True, verbose_name='Horizontal dilution of precision')),
                ('country', models.CharField(max_length=3)),
                ('registration_date', models.DateTimeField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
                ('uuid', models.CharField(max_length=100)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
