# Generated by Django 2.1.4 on 2018-12-14 09:24

import axgg.apps.adgg.validators
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adgg', '0002_auto_20181213_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, validators=[axgg.apps.adgg.validators.JsonSchemaValidator(limit_value={'day': {'type': 'integer'}, 'month': {'type': 'integer'}, 'year': {'required': True, 'type': 'integer'}})]),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='people', to='adgg.Household'),
        ),
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.CharField(choices=[('am', 'Amharic'), ('en', 'English'), ('fr', 'French'), ('sw', 'Swahili')], default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='organisation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('F', 'Farmer')], max_length=1), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
